CREATE TRIGGER A9
	ON LGLINE
	AFTER INSERT, DELETE,UPDATE
AS
BEGIN

	DECLARE @INV_NUM INT
	DECLARE @TOTAL INT

	IF (EXISTS (SELECT* FROM inserted))
	BEGIN
		
		DECLARE INSERTED_CURSOR CURSOR FOR
		SELECT INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS TOTAL
		FROM inserted
		GROUP BY inv_num

		OPEN INSERTED_CURSOR
		FETCH NEXT FROM INSERTED_CURSOR
			  INTO @INV_NUM, @TOTAL
		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE lginvoice
			SET INV_TOTAL = inv_total - @TOTAL
			WHERE inv_num = @INV_NUM
			FETCH NEXT FROM INSERTED_CURSOR
				  INTO @INV_NUM, @TOTAL
		END
		CLOSE INSERTED_CURSOR
		DEALLOCATE INSERTED_CURSOR
	END

	IF (EXISTS (SELECT* FROM deleted))

	BEGIN
		
		DECLARE DELETED_CURSOR CURSOR FOR
		SELECT INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS TOTAL
		FROM deleted
		GROUP BY inv_num

		OPEN DELETED_CURSOR
		FETCH NEXT FROM DELETED_CURSOR
			  INTO @INV_NUM, @TOTAL
		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE lginvoice
			SET INV_TOTAL = inv_total + @TOTAL
			WHERE inv_num = @INV_NUM
			FETCH NEXT FROM DELETED_CURSOR
				  INTO @INV_NUM, @TOTAL
		END
		CLOSE DELETED_CURSOR
		DEALLOCATE DELETED_CURSOR
	END
	END
