--65
SELECT BOOK_TITLE, BOOK_COST, BOOK_YEAR
FROM BOOK
--66
SELECT PAT_FNAME, PAT_LNAME
FROM PATRON
--67
SELECT CHECK_NUM, CHECK_OUT_DATE, CHECK_DUE_DATE
FROM CHECKOUT 
--68
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR
FROM BOOK
--69
SELECT DISTINCT BOOK_YEAR
FROM BOOK
--70
SELECT DISTINCT BOOK_SUBJECT
FROM BOOK
--71
SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST
FROM BOOK
--72
SELECT CHECK_NUM, BOOK_NUM, PAT_ID, CHECK_OUT_DATE, CHECK_DUE_DATE
FROM CHECKOUT
ORDER BY CHECK_OUT_DATE DESC
--73
SELECT BOOK_TITLE, BOOK_YEAR, BOOK_SUBJECT
FROM BOOK
ORDER BY BOOK_SUBJECT, BOOK_YEAR DESC, BOOK_TITLE
--74
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR
FROM BOOK
WHERE BOOK_YEAR = '2012'
--75
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR
FROM BOOK
WHERE BOOK_SUBJECT = 'Database'
--76
SELECT CHECK_NUM, BOOK_NUM, CHECK_OUT_DATE
FROM CHECKOUT
WHERE CHECK_OUT_DATE < '2015-04-5'
--77
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR
FROM BOOK
WHERE BOOK_YEAR > '2013' AND BOOK_SUBJECT = 'Programming'
--78
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR, BOOK_SUBJECT, BOOK_COST
FROM BOOK
WHERE (BOOK_SUBJECT = 'Middleware' or BOOK_SUBJECT = 'Cloud') AND (BOOK_COST > '70')
--79
SELECT AU_ID, AU_FNAME, AU_LNAME, AU_BIRTHYEAR
FROM AUTHOR
WHERE AU_BIRTHYEAR BETWEEN 1980 AND 1989
--80
SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR
FROM BOOK
WHERE BOOK_TITLE like '%Database%'
--81
SELECT PAT_ID, PAT_FNAME, PAT_LNAME
FROM PATRON
WHERE PAT_TYPE = 'STUDENT'
--82
SELECT PAT_ID, PAT_FNAME, PAT_LNAME
FROM PATRON
WHERE PAT_LNAME LIKE 'C%'
--83
SELECT AU_ID, AU_FNAME, AU_LNAME
FROM AUTHOR
WHERE AU_BIRTHYEAR IS NULL
--84
SELECT AU_ID, AU_FNAME, AU_LNAME
FROM AUTHOR
WHERE AU_BIRTHYEAR IS NOT NULL
--85
SELECT CHECK_NUM, BOOK_NUM, PAT_ID, CHECK_OUT_DATE, CHECK_DUE_DATE
FROM CHECKOUT
WHERE CHECK_IN_DATE IS NULL
ORDER BY BOOK_NUM
--86
SELECT AU_ID, AU_FNAME, AU_LNAME, AU_BIRTHYEAR
FROM AUTHOR
ORDER BY AU_BIRTHYEAR DESC, AU_LNAME
--87
SELECT COUNT (BOOK_NUM) [NUMBER OF BOOKS]
FROM BOOK
--88
SELECT COUNT (DISTINCT BOOK_SUBJECT) [NUMBER OF SUBJECTS]
FROM BOOK
--89
SELECT COUNT (BOOK_NUM) [AVAILABLE BOOKS]
FROM BOOK
WHERE PAT_ID IS NULL
--90
SELECT MAX (BOOK_COST) [MOST EXPENSIVE]
FROM BOOK
--91
SELECT MIN (BOOK_COST) [MOST EXPENSIVE]
FROM BOOK
--92
SELECT COUNT (DISTINCT P.PAT_ID) [DIFFERENT PATRONS]
FROM PATRON P INNER JOIN CHECKOUT C ON P.PAT_ID = C.PAT_ID
--SUBQUERY 
SELECT COUNT (DISTINCT PAT_ID) [DIFFERENT PATRONS]
FROM CHECKOUT 
WHERE PAT_ID IN (SELECT PAT_ID FROM PATRON)
--93 --problem
SELECT BOOK_SUBJECT, COUNT (*) AS 'BOOKS IN SUBJECT'
FROM BOOK
GROUP BY BOOK_SUBJECT
ORDER BY 'BOOKS IN SUBJECT' DESC, BOOK_SUBJECT
--94
SELECT AU_ID, COUNT(*) AS 'BOOKS WRITTEN'
FROM WRITES
GROUP BY AU_ID
ORDER BY 'BOOKS WRITTEN' DESC, AU_ID
--95
SELECT SUM (BOOK_COST) [LIBRARY VALUE]
FROM BOOK

